name       : libhandy
version    : 1.8.0
release    : 6
source     :
    - https://download.gnome.org/sources/libhandy/1.8/libhandy-1.8.0.tar.xz : 6c2542c0578924b0c29b7ae6cb44eb26df38eb01d6d5ef3d7d0b0825763230e8
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library full of GTK+ widgets for mobile phones
description: |
    Library full of GTK+ widgets for mobile phones
builddeps  :
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove not useful handy-1-demo binary
    rm -f %installroot%/usr/bin/handy-1-demo
    # Remove bin directory if otherwise empty (just in case something is added in the future)
    rmdir %installroot%/usr/bin
