name       : libhandy
version    : 1.5.0
release    : 1
source     :
    - https://download.gnome.org/sources/libhandy/1.5/libhandy-1.5.0.tar.xz : 466b9e026c1f9eb3b65966f530d97703a8212daaf911748c145e9cb843dbd6fe
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library full of GTK+ widgets for mobile phones
description: |
    Library full of GTK+ widgets for mobile phones
builddeps  :
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove not useful handy-1-demo binary
    rm -f %installroot%/usr/bin/handy-1-demo
    # Remove bin directory if otherwise empty (just in case something is added in the future)
    rmdir %installroot%/usr/bin
